### ISSUE TITLE
Missing libraries or references for C++ compiler with IE4K device

### ISSUE THREAD

**Issue by nie93** [CiscoIOx/docker-demo-apps#1]
Hi,

I go through every steps in the tutorial ![build-sample-docker-type-c-based-simple-app](https://developer.cisco.com/docs/iox/#tutorialbuild-sample-docker-type-c-based-simple-app) and try to deploy on IOx Sandbox, and it works fine with the c++ based codes.

But when I turn to deploy on the IE4000 switch, I change the url in `Dockerfile` to `FROM devhub-docker.cisco.com/iox-docker/ie4k/base-rootfs` to get the correct info. Then I try to test it by running the development tools image locally. When I use it to compile the c++ codes, the error messages shows missing libraries or links, as shown below:

``` sh
sgdril@ARPAE:~/nie/CiscoIoT/simple-cpp-app-ie4k$ pwd
/home/sgdril/nie/CiscoIoT/simple-cpp-app-ie4k
sgdril@ARPAE:~/nie/CiscoIoT/simple-cpp-app-ie4k$ docker run -v ${pwd}/apps:/opt/share -it ie4k-tools /bin/sh
/ # cd /opt/src/
/opt/src # ls -l
-rw-rw-r--    1 root     root           276 Jan 30 18:27 loop_app.cpp
-rw-rw-r--    1 root     root          8399 Jan 30 18:27 test-cpp-app.cpp
/opt/src # which g++
/usr/bin/g++
/opt/src # ls -l /usr/bin/g++
lrwxrwxrwx    1 root     root            22 Mar  9  2017 /usr/bin/g++ -> powerpc-poky-linux-g++
/opt/src # g++ test-cpp-app.cpp -o test-cpp-app
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__ltdf2@GLIBC_2.4'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__gtdf2@GLIBC_2.4'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__adddf3@GLIBC_2.3.2'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__fixunsdfsi@GLIBC_2.3.2'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__ltsf2@GLIBC_2.4'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__gtsf2@GLIBC_2.4'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__subdf3@GLIBC_2.3.2'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__eqdf2@GLIBC_2.3.2'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__floatunsidf@GLIBC_2.4'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__muldf3@GLIBC_2.3.2'
/usr/lib/gcc/powerpc-poky-linux/4.9.1/../../../../lib/libstdc++.so: undefined reference to `__extendsfdf2@GLIBC_2.3.2'
collect2: error: ld returned 1 exit status
/opt/src #
```

If there is any ways to solve this issue, please let me know.

Thanks,
Jack

**Comment by hgovind** [comment]
Hi Jack,


We have updated the image to the working version. Can you pull the updated base image and try to build the app.

To get the updated base image, use "--no-cache" flag while building an docker image or do the docker pull <image name>.


Thanks,

Harshal

________________________________

**Comment by nie93** [comment]
I tried to use `--no-cache` flag while building the image but it does not work. So I do the `docker pull devhub-docker.cisco.com/iox-docker/ie4k/base-rootfs:latest` command to update my local image, and after I rebuild the image, this issue no longer exists. 

Thanks @hgovind for your reply!
